// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvukBmaapwqLcI1lH-9Oq1MUF6gwu49Ps',
    appId: '1:693976677823:web:e2503bd5092bbb405bf50a',
    messagingSenderId: '693976677823',
    projectId: 'medischedule-e9c94',
    authDomain: 'medischedule-e9c94.firebaseapp.com',
    storageBucket: 'medischedule-e9c94.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8Ix4mKFOh12S-0h3ILrskGYX8j52rAwE',
    appId: '1:693976677823:android:2a7003fd43c7d2725bf50a',
    messagingSenderId: '693976677823',
    projectId: 'medischedule-e9c94',
    storageBucket: 'medischedule-e9c94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-mATr4WAc0Dn3lPDU3Gj1KzhJzqmuiLE',
    appId: '1:693976677823:ios:f154742a2572d0cb5bf50a',
    messagingSenderId: '693976677823',
    projectId: 'medischedule-e9c94',
    storageBucket: 'medischedule-e9c94.appspot.com',
    iosBundleId: 'com.example.g11AppointmentScheduling',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-mATr4WAc0Dn3lPDU3Gj1KzhJzqmuiLE',
    appId: '1:693976677823:ios:f154742a2572d0cb5bf50a',
    messagingSenderId: '693976677823',
    projectId: 'medischedule-e9c94',
    storageBucket: 'medischedule-e9c94.appspot.com',
    iosBundleId: 'com.example.g11AppointmentScheduling',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvukBmaapwqLcI1lH-9Oq1MUF6gwu49Ps',
    appId: '1:693976677823:web:211645fe570e456a5bf50a',
    messagingSenderId: '693976677823',
    projectId: 'medischedule-e9c94',
    authDomain: 'medischedule-e9c94.firebaseapp.com',
    storageBucket: 'medischedule-e9c94.appspot.com',
  );
}
